Merged PR 1556: Add/Update Active Issue tags as failing tests need deep investigation
For Issue #9196
Exception: `The login failed for user "u9bc9d4941d9843d29315f1db31d8cf8a". The password change failed. The user does not have permission to change the password.`
* This issue is reproducible locally by running the test with Multi threading, triggering 10 or more number of tasks together.
* The issue is not due to single database in use, I tested with random database generation in multiple threads, the exception still occurs. Which means if in any way someone tries to run the "Change Password" request in parallel using this driver, it will fail.
* Either the driver is doing something on the server that is causing this issue, or SQL Server is not handling requests well..

Possible Next Steps:
- Dig Deep into Change Password API logic and study server level changes if any.
- Check with SQL Server Team for assistance.
- Find a workaround to this test, or group all such tests together that can run only one at a time on target SQL Server.

For now, added Active Issue tag.